SET LIST ON;
SELECT COUNT(*) AS FV_TOTAL FROM DCTO WHERE TIP_DCTO='FV';
SELECT COUNT(*) AS FV_CON_NDO FROM DCTO WHERE TIP_DCTO='FV' AND NDO_DCTO IS NOT NULL AND TRIM(NDO_DCTO) <> '' AND TRIM(NDO_DCTO) <> '0';
SELECT FIRST 5 NUM_DCTO, NDO_DCTO, NUM_CONS, COD_CLIE FROM DCTO WHERE TIP_DCTO='FV' AND NDO_DCTO IS NOT NULL AND TRIM(NDO_DCTO) <> '' AND TRIM(NDO_DCTO) <> '0';
SELECT FIRST 5 NUM_DESP, COD_PROD, NOM_PROD, CAN_DESP, VTO_DESP FROM DESP ORDER BY NUM_DESP DESC;
SELECT COUNT(*) AS COINCIDENCIAS FROM DCTO c JOIN DESP d ON TRIM(c.NDO_DCTO) = CAST(CAST(d.NUM_DESP AS BIGINT) AS VARCHAR(20)) WHERE c.TIP_DCTO='FV';
